version: "3.8"
services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: always
    depends_on:
      rest_meals_api:
        condition: service_started
      diets_api:
        condition: service_started
      db:
        condition: service_healthy
  rest_meals_api:
    build: ./rest_meals_project/rest_meals_api
    volumes:
      - type: bind
        source: ./rest_meals_project/rest_meals_api
        target: /my_rest_meals_api
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      diets_api:
        condition: service_started
      db:
        condition: service_healthy
  diets_api:
    build: ./diets_project/diets_api
    volumes:
      - type: bind
        source: ./diets_project/diets_api
        target: /my_diets_api
    ports:
      - "5002:5002"
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    build: .
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
          - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-papi"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  mysql-data:
